### ISSUE TITLE
식객민우 필수입력필드 설정

### ISSUE THREAD

**Issue by kimkw92** [skyjland/politicannal-2016#11]
직책, 발언날짜, 발언 내용, 출처1 

필드에 값이 있어야 제출되게 수정 부탁
- 날짜만 입력하고 실수로 엔터 눌렀더니 DB에 입력돼버림

**Comment by kimkw92** [comment]
발언장소같은경우는 미확인인 경우가 간혹 있어서 괜찮

**Comment by kimkw92** [comment]
아냐아냐 이거 일단 보류

**Comment by skyjland** [comment]
ㅇㅋ
