### ISSUE TITLE
오른쪽 사이드도 만들어주세요.

### ISSUE THREAD

**Issue by kimkw92** [skyjland/politicannal-2016#14]
왼쪽만큼

**Comment by skyjland** [comment]
이건 좀 힘들지 않을까...왼쪽 사이드는 창 줄어들면서 맨 위 단축메뉴로 줄어드는데
오른쪽은 갈 곳이 없음...단축메뉴 2개 만드는것도 꽤 복잡하고..

**Comment by kimkw92** [comment]
pc에서 발언세부페이지에서도 사이드쪽 만들어주셔야함
