### ISSUE TITLE
수정 페이지

### ISSUE THREAD

**Issue by skyjland** [skyjland/politicannal-2016#5]
수정 페이지

**Comment by kimkw92** [comment]
db에서 바로 수정할 수 있는 방법은 없니

**Comment by kimkw92** [comment]
여러명이 DB접근하는것도 안되니까 구글 스프레드시트처럼 그냥 발언항목들 테이블에 쫙 뿌려주고 거기에 수정버튼 달려있는 페이지를 만들어줘 ㅜ
