### ISSUE TITLE
세부페이지 디자인

### ISSUE THREAD

**Issue by skyjland** [skyjland/politicannal-2016#6]
세부페이지 디자인

**Comment by kimkw92** [comment]
![image](https://cloud.githubusercontent.com/assets/16649896/14211821/120adb4e-f86b-11e5-9e21-ad5b78e61e41.png)
발언장소가 2줄이상으로 길 경우

![image](https://cloud.githubusercontent.com/assets/16649896/14211831/209863c0-f86b-11e5-8652-4556cd8b51fb.png)
발언장소 길이가 1줄이내 짧을 경우
