### ISSUE TITLE
인트로페이지 수정 

### ISSUE THREAD

**Issue by minjekrr** [skyjland/politicannal-2016#67]
![image](https://cloud.githubusercontent.com/assets/18205800/14309852/c9d09b36-fc19-11e5-860c-9023d4cc9249.png)

로고 크기 드라이브에 150logo파일로 수정해주시고 가운데 정렬 해주세요~~ (horizontal)
정치인 6명 링크 넣어주세요 (가나다)

**Comment by kimkw92** [comment]
박근혜 문재인 안철수 김무성 김문수 박원순   6명 ㄱㄷㄴ
